apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
  namespace: dev-test

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: robot
  namespace: dev-test
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: robot
  namespace: dev-test
subjects:
  - kind: ServiceAccount
    name: robot
    namespace: dev-test
roleRef:
  kind: Role
  name: robot
  apiGroup: rbac.authorization.k8s.io
