apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyborg
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cyborg
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cyborg
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
